export const config = {
  SPOTIFY_CLIENT_ID: process.env.VITE_SPOTIFY_CLIENT_ID,
  SPOTIFY_REDIRECT_URL: process.env.SPOTIFY_REDIRECT_URL,
  SPOTIFY_REDIRECT_PORT: process.env.SPOTIFY_REDIRECT_PORT,
};
